config/routes.rb
SeeAndShop::Application.routes.draw do
  get "users/new"

  get "users/edit"

  get "users/show"

  get "users/index"

  resources :shopping_areas

  resources :promos

  resources :stores

  resources :brands

  match '/promos_by_location', to: 'shopping_areas#promos_by_location', via: :post
  match '/facebook_token', to: 'users#create_from_facebook', via: :post
  match '/register_client', to: 'users#register_client', via: :post

  root :to => 'brands#index'

end

app/models/store.rb
# == Schema Information
#
# Table name: stores
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  brand_id         :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  phone            :string(255)
#  email            :string(255)
#  address          :string(255)
#  shopping_area_id :integer
#  longitude        :float
#  latitude         :float
#

class Store < ActiveRecord::Base
  attr_accessible :brand_id, :name, :phone, :email, :address, :shopping_area_id,
    :longitude, :latitude
  belongs_to :brand
  belongs_to :shopping_area
  has_many :promos
  has_many :store_promos
  has_many :promos, through: :store_promos

  validates :name, :email, :address, :latitude, :longitude, presence: true

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, format: { with: email_regex }

  def self.search(search)
    if search
      where('name LIKE upper(?) or phone LIKE (?) or address like (?)',
        "%#{search}%", "%#{search}%", "%#{search}%")
    else
      where("1=1")
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  respond_to :json, :html, :js
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.search(params[:search])
    respond_with(@stores)
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/new
  # GET /stores/new.json
  def new
    @store = Store.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store = Store.find(params[:id])
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(params[:store])
    @store.latitude = @store.shopping_area.latitude
    @store.longitude = @store.shopping_area.longitude
    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render json: @store, status: :created, location: @store }
      else
        format.html { render action: "new" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.json
  def update
    @store = Store.find(params[:id])
    @store.latitude = @store.shopping_area.latitude
    @store.longitude = @store.shopping_area.longitude
    respond_to do |format|
      if @store.update_attributes(params[:store])
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<div class="col-md-12">
  <%= f.input :name, label: "Nombre" %>
  <%= f.input :shopping_area_id, label: "Zona Comercial", collection:
    ShoppingArea.order(:name).map{ |p| [p.name,p.id]},
    input_html: {:class => "selectpicker", title: "Seleccionar..."} %>
  <%= f.input :brand_id, label: "Marca", input_html: {:class => "selectpicker",
    title: "Seleccionar..."}, collection: Brand.order(:name).map{ |p| [p.name,p.id]} %>
  <%= f.input :phone, label: "Telefono" %>
  <%= f.input :email, label: "Email" %>
  <%= f.input :address, label: "Direccion" %>
</div>

app/views/stores/_store.html.erb
<tr>
  <td><%= store.name.blank? ? "-" : store.name %></td>
  <td><%= store.brand.blank? ? "-" : store.brand.name %></td>
  <td><%= store.shopping_area.blank? ? "-" : store.shopping_area.name %></td>
  <td><%= store.phone.blank? ? "-" : store.phone %></td>
  <td><%= store.email.blank? ? "-" : store.email %></td>
  <td>
    <%= link_to(store, :class => 'btn btn-xs btn-primary', :title =>
        "Ver") do %>
            <span class= "glyphicon glyphicon-info-sign"></span>
        <% end %>
    <%= link_to(edit_store_path(store), :class =>
        'btn btn-default btn-xs', :title => "Editar") do %>
        <span class="glyphicon glyphicon-pencil"></span>
    <% end %>
    <%= link_to(store, method: :delete, data: { confirm:
            '¿Está seguro?' }, :class => 'btn btn-xs btn-danger', :title =>
            "Eliminar") do %>
            <span class="glyphicon glyphicon-trash"></span>
        <% end %>
    </td>
</tr>

app/views/stores/_stores_table.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
      <h3 class = "panel-title">Lista Tiendas</h3>
  </div>
  <table class="table table-striped table-bordered table-condensed">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Marca</th>
        <th>Zona Comercial</th>
        <th>Teléfono</th>
        <th>Email</th>
        <th width="95px"></th>
      </tr>
    </thead>
    <tbody>
      <%= render @stores %>
    </tbody>
  </table>
</div>

app/views/stores/edit.html.erb
<%= simple_form_for(@store) do |f| %>
  <%= f.error_notification %>
  <div class="col-sm-4 col-md-5 col-sm-offset-3 col-md-offset-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Editar Tienda</h3>
      </div>
      <div class="panel-body">
        <%= render 'form', :f => f %>
      </div>
      <div class="panel-footer">
        <%= f.submit "Guardar", :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/stores/index.html.erb
<% provide(:store, 'active') %>
<%= form_tag stores_path, :method => 'get', :id => "stores_search" do %>
  <div style="margin-left: 5px; margin-bottom: 15px;">
    <div class="input-group">
      <span class="input-group-addon" style="margin-right: -4px;">
        <span class="glyphicon glyphicon-search"></span>
      </span>
      <%= text_field_tag :search, params[:search], :class => 'form-control',
        :style => "width: 300px;", :placeholder => 'Buscar...' %>
    </div>
  </div>
  <div id="stores"> <%= render :partial => 'stores_table' %></div>
<% end %>

app/views/stores/index.js.erb
$('#stores').html("<%= escape_javascript(render("stores_table")) %>");

app/views/stores/new.html.erb
<%= simple_form_for(@store) do |f| %>
  <%= f.error_notification %>
  <div class="col-sm-4 col-md-5 col-sm-offset-3 col-md-offset-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Nueva Tienda</h3>
      </div>
      <div class="panel-body">
        <%= render 'form', :f => f %>
      </div>
      <div class="panel-footer">
        <%= f.submit "Guardar", :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/stores/show.html.erb
<div class="col-md-6 col-md-offset-3" id="show_brand">
  <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Tienda</h3>
      </div>
      <div class="panel-body">
        <table class="table table-user-information">
          <tbody>
            <tr>
              <td><strong>Nombre</strong></td>
              <td><%= @store.name.blank? ? "-" : @store.name %></td>
            </tr>
            <tr>
              <td><strong>Marca</strong></td>
              <td><%= @store.brand.blank? ? "-" : @store.brand.name %></td>
            </tr>
            <tr>
              <td><strong>Zona Comercial</strong></td>
              <td><%= @store.shopping_area.blank? ? "-" : @store.shopping_area.name %></td>
            </tr>
            <tr>
              <td><strong>Teléfono</strong></td>
              <td><%= @store.phone.blank? ? "-" : @store.phone %></td>
            </tr>
            <tr>
              <td><strong>Email</strong></td>
              <td><%= @store.email.blank? ? "-" : @store.email %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="panel-footer">
        <%= link_to "Editar", edit_store_path(@store),
          :class => 'btn btn-primary' %>
      </div>
    </div>
</div>