config/routes.rb
SeeAndShop::Application.routes.draw do
  get "users/new"

  get "users/edit"

  get "users/show"

  get "users/index"

  resources :shopping_areas

  resources :promos

  resources :stores

  resources :brands

  match '/promos_by_location', to: 'shopping_areas#promos_by_location', via: :post
  match '/facebook_token', to: 'users#create_from_facebook', via: :post
  match '/register_client', to: 'users#register_client', via: :post

  root :to => 'brands#index'

end

app/models/promo.rb
# == Schema Information
#
# Table name: promos
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  description        :text
#  brand_id           :integer
#  store_id           :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  start_date         :date
#  end_date           :date
#  restriction        :string(255)
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#  image_url          :string(255)
#

class Promo < ActiveRecord::Base
  attr_accessible :description, :brand_id, :name, :start_date, :end_date,
    :restriction, :image
  has_many :store_promos, dependent: :destroy
  has_many :stores, through: :store_promos
  belongs_to :brand

  has_attached_file :image, url: "/assets/images/promos/:id/:basename.:extension",
    :default_url => "no_picture.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :image, :attachment_presence => true
  validates :name, :description, :start_date, :end_date, :restriction, :brand_id,
    presence: true

  def self.search(search)
    if search
      where('name LIKE (?) or restriction LIKE (?) or description LIKE (?)',
        "%#{search}%", "%#{search}%", "%#{search}%")
    else
      where("1=1")
    end
  end
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
  respond_to :json, :html, :js

  def facebook_token
    token = params[:token]
    user_id = params[:user_id]
    user = FbGraph::User.fetch(user_id, :access_token => token)
    likes = user.likes
    Rails.logger.info "********LIKES*************"
    # if likes.include? :next
    #   puts "YES!!!!!!!!!"
    # end
    likes.each do |like|
      Rails.logger.info "#{like.inspect}"
      Rails.logger.info "#{like.category}"
      Rails.logger.info "#{like.name}"
    end
    @user = user.name
    UsersController.send_push_notification("aa")
    respond_to do |format|
      format.json { render json: @user}
    end
  end

  # GET /promos
  # GET /promos.json
  def index
    @promos = Promo.search(params[:search])
    @promos.each do |promo|
      promo[:brand_name] = promo.brand.name
      promo.image_url = promo.image
    end
    respond_with(@promos)
  end

  # GET /promos/1
  # GET /promos/1.json
  def show
    @promo = Promo.find(params[:id])
    @promo.image_url = @promo.image
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @promo }
    end
  end

  # GET /promos/new
  # GET /promos/new.json
  def new
    @promo = Promo.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @promo }
    end
  end

  # GET /promos/1/edit
  def edit
    @promo = Promo.find(params[:id])
  end

  # POST /promos
  # POST /promos.json
  def create
    @promo = Promo.new(params[:promo])
    brand = @promo.brand
    @promo.stores = brand.stores
    respond_to do |format|
      if @promo.save
        format.html { redirect_to @promo, notice: 'Promo was successfully created.' }
        format.json { render json: @promo, status: :created, location: @promo }
      else
        format.html { render action: "new" }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /promos/1
  # PUT /promos/1.json
  def update
    @promo = Promo.find(params[:id])
    brand = Brand.find(params[:promo][:brand_id])
    @promo.stores = brand.stores
    respond_to do |format|
      if @promo.update_attributes(params[:promo])
        format.html { redirect_to @promo, notice: 'Promo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promos/1
  # DELETE /promos/1.json
  def destroy
    @promo = Promo.find(params[:id])
    @promo.destroy

    respond_to do |format|
      format.html { redirect_to promos_url }
      format.json { head :no_content }
    end
  end

  def user_location
    #Esto hay que borrarlo!!!!!!!!!!!!!!
    Location.create!(:location => params[:latitude])
  end
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/promos/_form.html.erb
<div class="col-md-6">
  <div class="col-md-12">
    <%= f.input :name, label: "Nombre" %>
    <%= f.input :brand_id, label: "Marca", input_html: {:class => "selectpicker",
      title: "Seleccionar..."}, collection: Brand.order(:name).map{ |p| [p.name,p.id]} %>
  </div>
  <div class="col-md-6">
    <%= f.input :start_date, as: :string, input_html: {:class => "datepicker"},
      label: "Fecha Inicio" %>
  </div>
  <div class="col-md-6">
    <%= f.input :end_date, as: :string, input_html: {:class => "datepicker"},
      label: "Fecha Fin"%>
  </div>
  <div class="col-md-12">
    <%= f.file_field :image %>
  </div>
</div>
<div class="col-md-6">
  <div class="col-md-12">
    <%= f.input :description, input_html: {rows: 5, style: "resize: none"},
    label: "Descripción" %>
    <%= f.input :restriction, label: "Restricciones", as: :text, input_html:
      {rows: 5, style: "resize: none"} %>
  </div>
</div>

app/views/promos/_promo.html.erb
<tr>
  <td><%= promo.brand.blank? ? "-" : promo.brand.name %></td>
  <td><%= promo.name %></td>
  <td><%= promo.description.blank? ? "-" : promo.description %></td>
  <td><%= promo.restriction.blank? ? "-" : promo.restriction %></td>
  <td><%= promo.start_date.blank? ? "-" : promo.start_date %></td>
  <td><%= promo.end_date.blank? ? "-" : promo.end_date %></td>
  <td>
    <%= link_to(promo, :class => 'btn btn-xs btn-primary', :title =>
        "Ver") do %>
        <span class= "glyphicon glyphicon-info-sign"></span>
    <% end %>
    <%= link_to(edit_promo_path(promo), :class =>
        'btn btn-default btn-xs', :title => "Editar", disabled: false) do %>
        <span class="glyphicon glyphicon-pencil"></span>
    <% end %>
    <%= link_to(promo, method: :delete, data: { confirm:
        '¿Está seguro?' }, :class => 'btn btn-xs btn-danger', :title =>
        "Eliminar") do %>
        <span class="glyphicon glyphicon-trash"></span>
    <% end %>

  </td>
</tr>

app/views/promos/_promos_table.html.erb
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class = "panel-title">Lista Promociones</h3>
    </div>
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>Marca</th>
          <th>Nombre</th>
          <th>Descripción</th>
          <th>Restricciones</th>
          <th>Fecha Inicio</th>
          <th>Fecha Fin</th>
          <th width="95px"></th>
        </tr>
      </thead>
      <tbody>
        <%= render @promos %>
      </tbody>
    </table>
</div>

app/views/promos/edit.html.erb
<%= simple_form_for(@promo) do |f| %>
  <%= f.error_notification %>
  <div class="col-sm-10 col-md-10">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Editar Promocion</h3>
      </div>
      <div class="panel-body">
        <%= render 'form', :f => f %>
      </div>
      <div class="panel-footer">
        <%= f.submit "Guardar", :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/promos/index.html.erb
<% provide(:promo, 'active') %>
<%= form_tag promos_path, :method => 'get', :id => "promos_search" do %>
  <div style="margin-left: 5px; margin-bottom: 15px;">
    <div class="input-group">
      <span class="input-group-addon" style="margin-right: -4px;">
        <span class="glyphicon glyphicon-search"></span>
      </span>
      <%= text_field_tag :search, params[:search], :class => 'form-control',
        :style => "width: 300px;", :placeholder => 'Buscar...' %>
    </div>
  </div>
  <div id="promos"> <%= render :partial => 'promos_table' %></div>
<% end %>

app/views/promos/index.js.erb
$('#promos').html("<%= escape_javascript(render("promos_table")) %>");

app/views/promos/new.html.erb
<%= simple_form_for(@promo) do |f| %>
  <%= f.error_notification %>
  <div class="col-sm-10 col-md-10">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Nueva Promocion</h3>
      </div>
      <div class="panel-body">
        <%= render 'form', :f => f %>
      </div>
      <div class="panel-footer">
        <%= f.submit "Guardar", :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/promos/show.html.erb
<div class="col-md-12" id="show_promo">
  <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Promoción</h3>
      </div>
      <div class="panel-body">
        <div class="col-md-6">
          <%= image_tag @promo.image.url,
            :class=>"img-responsive img-rounded", size: "350x350" %>
        </div>
        <div class="col-md-6">
          <table class="table table-user-information">
            <tbody>
              <tr>
                <td><strong>Nombre</strong></td>
                <td><%= @promo.name.blank? ? "-" : @promo.name %></td>
              </tr>
              <tr>
                <td><strong>Marca</strong></td>
                <td><%= @promo.brand.blank? ? "-" : @promo.brand.name %></td>
              </tr>
              <tr>
                <td><strong>Descripción</strong></td>
                <td><%= @promo.description.blank? ? "-" : @promo.description %></td>
              </tr>
              <tr>
                <td><strong>Restricciones</strong></td>
                <td><%= @promo.restriction.blank? ? "-" : @promo.restriction %></td>
              </tr>
              <tr>
                <td><strong>Fecha Inicio</strong></td>
                <td><%= @promo.start_date.blank? ? "-" : @promo.start_date %></td>
              </tr>
              <tr>
                <td><strong>Fecha Fin</strong></td>
                <td><%= @promo.end_date.blank? ? "-" : @promo.end_date %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="panel-footer">
        <%= link_to "Editar", edit_promo_path(@promo),
          :class => 'btn btn-primary', disabled: false %>
      </div>
    </div>
</div>

app/views/promos/user_location.html.erb
<%=  @user_location %>