config/routes.rb
SeeAndShop::Application.routes.draw do
  get "users/new"

  get "users/edit"

  get "users/show"

  get "users/index"

  resources :shopping_areas

  resources :promos

  resources :stores

  resources :brands

  match '/promos_by_location', to: 'shopping_areas#promos_by_location', via: :post
  match '/facebook_token', to: 'users#create_from_facebook', via: :post
  match '/register_client', to: 'users#register_client', via: :post

  root :to => 'brands#index'

end

app/models/brand.rb
# == Schema Information
#
# Table name: brands
#
#  id                  :integer          not null, primary key
#  name                :string(255)
#  description         :text
#  email               :string(255)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  web_page            :string(255)
#  nit                 :string(255)
#  phone               :string(255)
#  avatar_file_name    :string(255)
#  avatar_content_type :string(255)
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  image_url           :string(255)
#

class Brand < ActiveRecord::Base
  attr_accessible :description, :email, :name, :web_page, :nit, :phone, :avatar
  has_many :stores, :dependent => :destroy
  has_many :promos
  has_attached_file :avatar, url: "/assets/images/brands/:id/:basename.:extension",
    :default_url => "no_picture.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates :name, :nit, :email, presence: true
  validates :avatar, :attachment_presence => true

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, format: { with: email_regex }

  def self.search(search)
    if search
      where('name LIKE upper(?) or email LIKE (?) or description LIKE (?) or
        web_page LIKE (?) or nit LIKE (?) or phone LIKE (?)', "%#{search}%",
        "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      where("1=1")
    end
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  respond_to :json, :html, :js
  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.search(params[:search])
    @brands.each do |brand|
      brand.image_url = brand.avatar
    end
    respond_with(@brands)
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.find(params[:id])
    @brand.image_url = @brand.avatar
    @brand.promos.each do |promo|
      promo.image_url = promo.image
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json {render json: @brand.to_json(
        only: [:name, :email, :image_url,:id, :phone, :web_page, :nit,
          :description],
        include: [:promos, stores: {
          only: [:address, :email, :id, :name],
          include: {shopping_area: {only:[:name, :city, :longitude, :latitude,
            :description, :address]}}
        }]
      )}
    end
  end

  # GET /brands/new
  # GET /brands/new.json
  def new
    @brand = Brand.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(params[:brand])
    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render json: @brand, status: :created, location: @brand }
      else
        format.html { render action: "new" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brands/1
  # PUT /brands/1.json
  def update
    @brand = Brand.find(params[:id])
    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_brand.html.erb
<tr>
  <td><%= brand.name.blank? ? "-" : brand.name %></td>
  <td><%= brand.nit.blank? ? "-" : brand.nit %></td>
  <td><%= brand.phone.blank? ? "-" : brand.phone %></td>
  <td><%= brand.email.blank? ? "-" : brand.email %></td>
  <td><%= brand.web_page.blank? ? "-" : brand.web_page %></td>
  <td><%= brand.description.blank? ? "-" : brand.description %></td>
  <td>
    <%= link_to(brand, :class => 'btn btn-xs btn-primary', :title =>
        "Ver") do %>
            <span class= "glyphicon glyphicon-info-sign"></span>
        <% end %>
    <%= link_to(edit_brand_path(brand), :class =>
        'btn btn-default btn-xs', :title => "Editar") do %>
        <span class="glyphicon glyphicon-pencil"></span>
    <% end %>
    <%= link_to(brand, method: :delete, data: { confirm:
            '¿Está seguro?' }, :class => 'btn btn-xs btn-danger', :title =>
            "Eliminar") do %>
            <span class="glyphicon glyphicon-trash"></span>
        <% end %>
    </td>
</tr>

app/views/brands/_brands_table.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
      <h3 class = "panel-title">Lista Marcas</h3>
  </div>
  <table class="table table-striped table-bordered table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Nit</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Web Page</th>
        <th>Description</th>
        <th width="95px"></th>
      </tr>
    </thead>
    <tbody>
      <%= render @brands %>
    </tbody>
  </table>
</div>

app/views/brands/_form.html.erb
<div class="col-md-6">
  <%= f.input :name, label: "Nombre" %>
  <%= f.input :nit %>
  <%= f.input :phone %>
  <%= f.input :email, as: :email %>
  <%= f.input :web_page %>
  <%= f.file_field :avatar %>
</div>
<div class="col-md-6">
  <%= f.input :description, label: "Descripción", input_html: {cols: 39, rows: 11,
    style: "resize: none"}%>
</div>

app/views/brands/edit.html.erb
<%= simple_form_for(@brand)  do |f| %>
  <%= f.error_notification %>
  <div class="col-sm-10 col-md-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">
          Editar Marca
        </h3>
      </div>
      <div class="panel-body">
        <%= render 'form', :f => f %>
      </div>
      <div class="panel-footer">
        <%= f.submit "Guardar", :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/brands/index.html.erb
<% provide(:brand, 'active') %>
<%= form_tag brands_path, :method => 'get', :id => "brands_search" do %>
  <div style="margin-left: 5px; margin-bottom: 15px;">
    <div class="input-group">
      <span class="input-group-addon" style="margin-right: -4px;">
        <span class="glyphicon glyphicon-search"></span>
      </span>
      <%= text_field_tag :search, params[:search], :class => 'form-control',
        :style => "width: 300px;", :placeholder => 'Buscar...' %>
    </div>
  </div>
  <div id="brands"> <%= render :partial => 'brands_table' %></div>
<% end %>

app/views/brands/index.js.erb
$('#brands').html("<%= escape_javascript(render("brands_table")) %>");

app/views/brands/new.html.erb
<%= simple_form_for(@brand)  do |f| %>
  <%= f.error_notification %>
  <div class="col-sm-10 col-md-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">
          Nueva Marca
        </h3>
      </div>
      <div class="panel-body">
        <%= render 'form', :f => f %>
      </div>
      <div class="panel-footer">
        <%= f.submit "Guardar", :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/brands/show.html.erb
<div class="col-md-12" id="show_brand">
  <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Marca</h3>
      </div>
      <div class="panel-body">
        <div class="col-md-6">
          <%= image_tag @brand.avatar.url,
            :class=>"img-responsive img-rounded", size: "350x350" %>
        </div>
        <div class="col-md-6">
          <table class="table table-user-information">
            <tbody>
              <tr>
                <td><strong>Nombre</strong></td>
                <td><%= @brand.name.blank? ? "-" : @brand.name %></td>
              </tr>
              <tr>
                <td><strong>NIT</strong></td>
                <td><%= @brand.nit.blank? ? "-" : @brand.nit %></td>
              </tr>
              <tr>
                <td><strong>Telefono</strong></td>
                <td><%= @brand.phone.blank? ? "-" : @brand.phone %></td>
              </tr>
              <tr>
                <td><strong>Email</strong></td>
                <td><%= @brand.email.blank? ? "-" : @brand.email %></td>
              </tr>
              <tr>
                <td><strong>Pagina Web</strong></td>
                <td><%= @brand.web_page.blank? ? "-" : @brand.web_page %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="panel-footer">
        <%= link_to "Editar", edit_brand_path(@brand),
          :class => 'btn btn-primary' %>
      </div>
    </div>
</div>