config/routes.rb
SeeAndShop::Application.routes.draw do
  get "users/new"

  get "users/edit"

  get "users/show"

  get "users/index"

  resources :shopping_areas

  resources :promos

  resources :stores

  resources :brands

  match '/promos_by_location', to: 'shopping_areas#promos_by_location', via: :post
  match '/facebook_token', to: 'users#create_from_facebook', via: :post
  match '/register_client', to: 'users#register_client', via: :post

  root :to => 'brands#index'

end

app/views/layouts/_side_menu.html.erb
    <div class="col-sm-3 col-md-2 affix-sidebar" id="sideBar">
    <div class="sidebar-nav">
  <div class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <span class="visible-xs navbar-brand">See&Shop</span>
    </div>
    <div class="navbar-collapse collapse sidebar-navbar-collapse">
      <ul class="nav navbar-nav" id="sidenav01">
        <li class="menu-head">
          <a href="#" data-toggle="collapse" data-target="#toggleDemo0" data-parent="#sidenav01">
            <h4>
            Admin
            <br>
            <small>administrator</small>
            </h4>
          </a>
        </li>
        <li>
          <a href="#" data-toggle="collapse" data-target="#toggle_shopping_area"
            data-parent="#sidenav01" class="module tree-toggler">
            <span class="glyphicon glyphicon-chevron-right"></span> Zona Comercial
            <span class="caret pull-right"></span>
          </a>
          <div class="collapse" id="toggle_shopping_area" style="height: 0px;">
            <ul class="nav nav-list">
              <li>
                <%= link_to "  Nuevo", new_shopping_area_path,
                  :class => "glyphicon glyphicon-plus sub-module"%>
              </li>
              <li>
                <%= link_to "  Lista", shopping_areas_path,
                  :class => "glyphicon glyphicon-th-list sub-module" %>
              </li>
            </ul>
          </div>
        </li>
        <li>
          <a href="#" data-toggle="collapse" data-target="#toggle_brand"
            data-parent="#sidenav01" class="tree-toggler module">
            <span class="glyphicon glyphicon-chevron-right"></span> Marcas
            <span class="caret pull-right"></span>
          </a>
          <div class="collapse" id="toggle_brand" style="height: 0px;">
            <ul class="nav nav-list">
              <li><%= link_to "  Nuevo", new_brand_path,
                :class => "glyphicon glyphicon-plus sub-module" %></li>
              <li><%= link_to "  Lista", brands_path,
                :class => "glyphicon glyphicon-th-list sub-module" %></li>
            </ul>
          </div>
        </li>
        <li>
          <a href="#" data-toggle="collapse" data-target="#toggle_store"
            data-parent="#sidenav01" class="module tree-toggler">
            <span class="glyphicon glyphicon-chevron-right"></span> Tiendas
            <span class="caret pull-right"></span>
          </a>
          <div class="collapse" id="toggle_store" style="height: 0px;">
            <ul class="nav nav-list">
              <li><%= link_to "  Nuevo", new_store_path,
                :class => "glyphicon glyphicon-plus sub-module" %></li>
              <li><%= link_to "  Lista", stores_path,
                :class => "glyphicon glyphicon-th-list sub-module" %></li>
            </ul>
          </div>
        </li>
        <li>
          <a href="#" data-toggle="collapse" data-target="#toggle_promo"
            data-parent="#sidenav01" class="module tree-toggler">
            <span class="glyphicon glyphicon-chevron-right"></span> Promos
            <span class="caret pull-right"></span>
          </a>
          <div class="collapse" id="toggle_promo" style="height: 0px;">
            <ul class="nav nav-list">
              <li><%= link_to "  Nuevo", new_promo_path,
                :class => "glyphicon glyphicon-plus sub-module" %></li>
              <li><%= link_to "  Lista", promos_path,
                :class => "glyphicon glyphicon-th-list sub-module" %></li>
            </ul>
          </div>
        </li>
        <li><a href="" class="module"><span class="glyphicon glyphicon-cog"></span> PreferencesMenu</a></li>
      </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeeAndShop</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
  <%= stylesheet_link_tag "application", controller_name, :media => "all" %>
  <%= javascript_include_tag "application", controller_name %>
  <%= csrf_meta_tags %>
  <meta charset='utf-8'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--[if IE]><link rel="SHORTCUT ICON" href="/assets/icon.ico"/><![endif]--><!-- Internet Explorer-->
</head>
<body>
  <div class="row affix-row">
    <%= render 'layouts/side_menu'%>
    <div class="col-sm-9 col-md-10 affix-content">
      <div class="container" style ="margin-top:20px">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>